- hosts: all
  become: true
  tasks:
    - name: update index repository (Ubuntu)
      apt:
        update_cache: true
      when: ansible_os_family == "Ubuntu"

- hosts: all
  become: true
  roles:
    - ../roles/bootstrap
    # - ../roles/common
    # - ../roles/backend

# - hosts: web
#   become: true
#   roles:
#     - ../roles/backend