- name: Install Nginx on web remote server
  hosts: web
  become: true # Use sudo to run tasks as root

  tasks:
    - name: Update list of apt packages (Just with Ubuntu/Debian)
      tags:
        - frontend
      apt:
        update_cache: yes

    - name: Install Nginx (Ubuntu/Debian)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Stop Nginx service (Ubuntu/Debian)
      tags:
        - frontend
      service:
        name: nginx
        state: stopped
      when: ansible_os_family == "Debian"